Script ibov tickers
rafaelquintanilha/quantbrasil-api pull request #5
Opened 2021-04-20 19:31 UTC by andressa-monteiro

2021-04-20 20:12 UTC, rafaelquintanilha requested changes
Muito bom mesmo. Fiz alguns comentários pra melhorar performance e legibilidade do código

2021-04-20 20:12 UTC, rafaelquintanilha commented on db.py
> +from dotenv import load_dotenv, find_dotenv
Você não está usando `find_dotenv`, então não precisa importar

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +import pandas as pd
Dá um nome mais específico: `update_db.py` pode ser pra qualquer coisa. Nesse caso, você está atualizando apenas o portfolio IBOV.

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +from dotenv import load_dotenv, find_dotenv
De novo, não precisa do `find_dotenv`

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +path_to_file = glob.glob(f"{downloads_dir_path}*.csv")
Não é errado, mas o melhor é colocar o path sem a barra final `/`. Daí ficaria: `f"{downloads_dir_path}/*.csv"`

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +portfolio_from_sql = pd.read_sql('portfolio', engine)
Aqui você tá buscando todos os portfólios no banco de dados. Mas você só quer atualizar um: `IBOV`. Por que não colocar a condição diretamente aqui?

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +participation["weight"] = participation["weight"] / 100
Não se esquece de dar um round pra 4 casas decimais.

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +asset_from_sql = pd.read_sql('asset', engine, columns=['id','symbol'])
Você precisa buscar todos os assets? Você não acabou de inserir no banco de dados?

2021-04-20 20:12 UTC, rafaelquintanilha commented on scripts/update_db.py
> +participation["weight"] = participation["weight"] / 100
Agora vi que você fez ali em baixo. Não estaria errado, mas como você formatou (dividiu por 100) aqui, o ideal seria já fazer o round aqui de uma vez. Do contrário você está formatando em 2 lugares diferentes.

2021-04-21 19:29 UTC, andressa-monteiro commented on scripts/update_db.py
> +path_to_file = glob.glob(f"{downloads_dir_path}*.csv")
Com a barra então, né?!

2021-04-21 20:39 UTC, rafaelquintanilha requested changes
Muito bom!! Fiz dois comentários muito pequenos. Outra coisa é pra deletar esse arquivo `.DS_Store`. Ele é específico do Mac e não deve estar no repositório. Outra alternativa é colocar ele no `.gitignore`

2021-04-21 20:39 UTC, rafaelquintanilha commented on scripts/upd_ibov_portfolio.py
> +        .format(row.Código, row.Ação, row.Tipo, row.YF_Código)
Usa sempre esse formato:`row["Código"]`. A gente viu que sem isso pode dar problema dependendo do nome da coluna, sem falar que se tivesse espaço no nome não funcionaria.

2021-04-21 20:39 UTC, rafaelquintanilha commented on scripts/upd_ibov_portfolio.py
> +    f"SELECT id, symbol FROM asset WHERE symbol IN {symbol_tuple };",
Tem um espaço a mais

2021-04-22 18:37 UTC, rafaelquintanilha commented on README.md
> +- one with the chromedriver path;
Qual o nome da variável?

2021-04-22 18:52 UTC, rafaelquintanilha requested changes
Quase lá. Deixei umas sugestões pro código ficar ainda melhor

2021-04-22 18:52 UTC, rafaelquintanilha commented on scripts/create_db.py
> +insert_portfolio_query = "INSERT INTO portfolio (name) VALUES ('IBOV'), ('BDR');"
Muito bom! Só uma questão conceitual:

`create_db` é responsável por criar as tabelas e seus relacionamentos, isso está certo.

Porém, você está usando esse mesmo código pra popular parte do banco (criando `IBOV` e `BDR`). Idealmente isso ficaria em outro arquivo.

Suponha que daqui a 1 semana a gente decida fazer um portfólio com os ativos do índice de materiais (IMAT). Como eu faria pra rodar o script? Eu precisaria rodar alterar e rodar `create_db`, sendo que ele não tem nada a ver com a história.

2021-04-22 18:52 UTC, rafaelquintanilha commented on utils.py
>  def get_ibov_tickers():
Muito bom. Dá pra melhorar essa função: concorda que ela tá pegando todos os ativos relacionados a um portfólio específico do banco? Então por que não parametrizar a função?

Você usaria ela assim:

```
ibov = get_tickers("IBOV")
bdr = get_tickers("BDR")
```

2021-04-23 14:47 UTC, rafaelquintanilha approved these changes
Parabéns!!

2021-04-23 14:48 UTC, merged